"""registro de intentos de login (login_attempts)

Revision ID: 450e59d38817
Revises: e04bab145e52
Create Date: 2026-07-24 05:59:31.913613
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '450e59d38817'
down_revision: Union[str, None] = 'e04bab145e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username_claimed', sa.String(length=80), nullable=False),
    sa.Column('result', sa.Enum('success', 'failure', 'locked', name='login_attempt_result'), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Nota: el autogenerate también proponía dropear ix_photos_trip_id_visibility,
    # ix_trips_search_vector e ix_trips_title_trgm — mismo falso positivo que en
    # migraciones anteriores (53117a0e8891, e04bab145e52): esos índices se crearon
    # con op.execute() crudo y no están declarados como Index() en los modelos.
    # Se ignoran intencionalmente.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_attempts')
    op.execute("DROP TYPE login_attempt_result")
    # ### end Alembic commands ###
