"""modelo de datos de contenido

Revision ID: cbbc0ac46e0c
Revises: 
Create Date: 2026-07-22 08:13:29.150152
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cbbc0ac46e0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pg_trgm habilita el índice de trigramas usado en la búsqueda de
    # títulos (SPEC-MASTER §7.3); se instala aquí porque esta es la primera
    # migración que la necesita.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('cover_photo_id', sa.UUID(), nullable=True),
    sa.Column('place', sa.String(length=200), nullable=True),
    sa.Column('trip_start', sa.Date(), nullable=True),
    sa.Column('trip_end', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='trip_status'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('original_path', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gps_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('gps_lon', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('visibility', sa.Enum('private', 'public', name='photo_visibility'), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('alt_text', sa.String(length=300), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'content_hash', name='uq_photos_trip_content_hash')
    )
    op.create_table('trip_tags',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_id', 'tag_id')
    )
    op.create_table('photo_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('thumb', 'medium', 'large', name='photo_variant_kind'), nullable=False),
    sa.Column('format', sa.Enum('webp', 'jpeg', 'avif', name='photo_variant_format'), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # cover_photo_id -> photos.id se añade aquí, tras crear 'photos', para
    # romper el ciclo trips <-> photos (RF-R1-14): use_alter en el modelo
    # SQLAlchemy solo evita que autogenerate la incluya en create_table de
    # 'trips', pero no emite el ALTER TABLE por sí solo dentro de una
    # migración de Alembic, así que hay que crearla explícitamente.
    op.create_foreign_key(
        "fk_trips_cover_photo_id",
        "trips",
        "photos",
        ["cover_photo_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # Índices clave de SPEC-MASTER §7.3 no capturados por el autogenerate
    # (GIN/trigram): búsqueda de viajes y listado de fotos por visibilidad.
    op.execute("CREATE INDEX ix_trips_search_vector ON trips USING gin (search_vector)")
    op.execute("CREATE INDEX ix_trips_title_trgm ON trips USING gin (title gin_trgm_ops)")
    op.create_index("ix_photos_trip_id_visibility", "photos", ["trip_id", "visibility"])


def downgrade() -> None:
    op.drop_index("ix_photos_trip_id_visibility", table_name="photos")
    op.execute("DROP INDEX IF EXISTS ix_trips_title_trgm")
    op.execute("DROP INDEX IF EXISTS ix_trips_search_vector")

    # Elimina primero la FK que rompe el ciclo, antes de poder dropear
    # 'photos' (referenciada por 'trips.cover_photo_id').
    op.drop_constraint("fk_trips_cover_photo_id", "trips", type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_variants')
    op.drop_table('trip_tags')
    op.drop_table('photos')
    op.drop_table('trips')
    op.drop_table('topics')
    op.drop_table('tags')
    op.drop_table('audit_log')
    # ### end Alembic commands ###

    # op.drop_table() no elimina los tipos ENUM nativos que usaron esas
    # columnas: hay que borrarlos explícitamente o un upgrade posterior
    # falla con "type already exists".
    op.execute("DROP TYPE photo_variant_format")
    op.execute("DROP TYPE photo_variant_kind")
    op.execute("DROP TYPE photo_visibility")
    op.execute("DROP TYPE trip_status")
