"""bloqueo de cuentas (account_locks)

Revision ID: e04bab145e52
Revises: 53117a0e8891
Create Date: 2026-07-24 05:21:07.784017
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e04bab145e52'
down_revision: Union[str, None] = '53117a0e8891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_locks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consecutive_locks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Nota: el autogenerate también proponía dropear ix_photos_trip_id_visibility,
    # ix_trips_search_vector e ix_trips_title_trgm — mismo falso positivo que en
    # la migración anterior (53117a0e8891): esos índices se crearon con
    # op.execute() crudo y no están declarados como Index() en los modelos.
    # Se ignoran intencionalmente.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_locks')
    # ### end Alembic commands ###
